### ISSUE TITLE
Cannot resolve module 'vue-paginate'

### ISSUE THREAD

**Issue by SeavantUUz** [TahaSh/vue-paginate#8]
I followed the steps what you had said in README, like this:  `Vue.use(require('vue-paginate'));`
But when I executed webpack, I got error messages and webpack complained the error.

```
Module not found: Error: Cannot resolve module 'vue-paginate' in /User/path/my_js_dir
 @ ./src/js/myscript.js 18:18-41
```

*myscript.js* is the js script file where I imported vue-paginate in.

So I decided to change the using way.  `Vue.use(require('vue-paginate/dist/vue-paginate.js'))`.

Now, although webpack complained some warning messages, I passed whole compiling procedure.
But this time, my browser told me `plugin.apply is not a function`. 
I would paste context codes in there:

```javascript
Vue.use = function (plugin) {
	    /* istanbul ignore if */
	    if (plugin.installed) {
	      return;
	    }
	    // additional parameters
	    var args = toArray(arguments, 1);
	    args.unshift(this);
	    if (typeof plugin.install === 'function') {
	      plugin.install.apply(plugin, args);
	    } else {
	      plugin.apply(null, args); < ---------- There
	    }
	    plugin.installed = true;
	    return this;
	  };
```

How does this problem happen?
Maybe the index.js of vue-paginate module should be contained in an immediately-invoked function?

THX.

My environments:
* npm 3.8.9
* Vue 1.0.24
* vue-paginate 2.1.0
* webpack 1.13.1 -- add babel loader. `{ test: /\.jsx?$/,   exclude: /(node_modules|bower_components)/, loader: 'babel?presets[]=es2015'},`

**Comment by SeavantUUz** [comment]
If you didn't set UglifyJsPlugin in webpack, everything is ok.
I would ignore the error messages which emerged in UglifyJsPlugin of webpack.
So you could close this issue.

**Comment by markeilander** [comment]
I have the same issue.
Can't find any solution yet..

**Comment by TahaSh** [comment]
Hey guys! Thanks for filling this issue. Actually, this error occurs because I'm not compiling the plugin properly. This now should be fixed, just update to version 2.1.1.

Thanks for using the plugin :).

**Comment by markeilander** [comment]
The error remains to exist.. after update to 2.1.1
